---
# Allow access to the webhook server.
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-webhook-traffic
  namespace: openshift-ptp
spec:
  ingress:
    - ports:
        - port: 9443
          protocol: TCP
        - port: 443
          protocol: TCP
  podSelector:
    matchLabels:
      name: ptp-operator  # Target only ptp-operator Pods (adjust if needed)
  policyTypes:
    - Ingress
    - Egress
